version: '3.5'
services:
  backend:
    build: ./backend
    container_name: chess-backend
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    container_name: chess-frontend
    ports:
        - '4200:4200' # Port mapping
    links:
      - backend
